import { FAQData } from '@/types/faq';

export const initialFaqSeedData: FAQData = {
    categories: [
        { id: "static-voltage-regulators", name: "Static Voltage Regulators", order: 1 },
        { id: "servo-stabilisers", name: "Servo Stabilisers", order: 2 },
        { id: "isolation-transformers", name: "Isolation Transformers", order: 3 },
        { id: "alensoft-enms", name: "ALENSOFT EnMS", order: 4 },
        { id: "ups", name: "UPS Systems", order: 5 },
        { id: "power-quality-analyzers", name: "Power Quality Analyzers", order: 6 },
        { id: "multifunction-power-quality-meters", name: "Multifunction & Power Quality Meters", order: 7 },
        { id: "thermal-imaging-cameras", name: "Thermal Imaging & Cameras", order: 8 },
        { id: "installation-safety-testers", name: "Installation & Safety Testers", order: 9 }
    ],
    // Questions will be populated below to keep the file cleaner
    questions: []
};

// Helper to add questions
const addQ = (categoryId: string, q: string, a: string) => {
    const currentCount = initialFaqSeedData.questions.filter(qu => qu.categoryId === categoryId).length;
    initialFaqSeedData.questions.push({
        id: `${categoryId}-q${currentCount + 1}`,
        categoryId,
        question: q,
        answer: a,
        order: currentCount + 1,
        createdAt: new Date().toISOString()
    });
};

// 1. Static Voltage Regulators
addQ("static-voltage-regulators", "What is a static voltage regulator?", "Static Voltage voltage regulator is a solid-state voltage regulation system that uses IGBT Based advanced power electronics to deliver stable output voltage with very fast response, making it ideal for dynamic and sensitive loads.");
addQ("static-voltage-regulators", "How does static voltage regulator work?", "Static voltage regulators continuously monitor the output voltage using high-speed digital control. When a deviation is detected, solid-state switching devices instantly correct the voltage without any mechanical movement.");
addQ("static-voltage-regulators", "What are the key advantages of Krykard static voltage regulators?", "Krykard static voltage regulators offer: Ultra-fast response time, No moving parts, Compact design, and Stable output for rapidly fluctuating supply conditions.");
addQ("static-voltage-regulators", "Where are Krykard static voltage regulators typically used?", "They are ideal for: CNC & VMC machines, Welding Robots, Plasma Welding Machine, Laser Cutting Machine, Semiconductor & electronics manufacturing, Medical imaging equipment, Data centres & IT infrastructure, and Precision automation systems.");
addQ("static-voltage-regulators", "What output voltage accuracy do Krykard static voltage regulators provide?", "Krykard static voltage regulators typically provide ±1% output voltage regulation, suitable for highly sensitive electronic loads.");
addQ("static-voltage-regulators", "How fast is the response time of Krykard static voltage regulators?", "Krykard static voltage regulators correct any voltage variation within its input voltage range within milliseconds, ensuring excellent protection against sudden voltage dips, surges, and transients.");
addQ("static-voltage-regulators", "Are Krykard static voltage regulators suitable for nonlinear and dynamic loads?", "Yes. Krykard static voltage regulators are well suited for nonlinear, rapidly varying loads such as VFD-driven systems and electronic power supplies.");
addQ("static-voltage-regulators", "Can Krykard static voltage regulators be used for residential applications?", "Yes. Krykard static voltage regulators can be used for residential applications. They are well-suited for homes where voltage fluctuations are common and reliable power protection is needed. They provide stable voltage output to protect home appliances, low maintenance requirements, silent operation, and high efficiency.");
addQ("static-voltage-regulators", "Do Krykard static voltage regulators generate harmonics?", "Krykard static voltage regulators are designed with advanced filtering and control algorithms to minimize harmonic impact and meet applicable EMC requirements.");
addQ("static-voltage-regulators", "What is the efficiency of Krykard static voltage regulators?", "Krykard static voltage regulators are engineered for high operating efficiency, typically above 96–98%, depending on rating and operating conditions.");
addQ("static-voltage-regulators", "Can Krykard static voltage regulators handle frequent voltage fluctuations?", "Yes. Krykard static voltage regulators are specifically designed for high-frequency voltage variations commonly seen in modern industrial power systems.");
addQ("static-voltage-regulators", "Are Krykard static voltage regulators available in three-phase versions?", "Yes. Krykard static voltage regulators are available in single-phase, three-phase balanced, and three-phase unbalanced configurations.");
addQ("static-voltage-regulators", "Can Krykard static voltage regulators operate with DG sets and UPS systems?", "Yes. Krykard static voltage regulators are compatible with DG sets and UPS-backed power systems, helping maintain stable voltage during load transitions.");
addQ("static-voltage-regulators", "What protection features are provided in Krykard static voltage regulators?", "Standard protections include: Over-voltage and under-voltage protection, Overload and short-circuit protection, Phase failure and phase sequence protection (3-phase), Surge & Spike protection, and Thermal protection for the IGBTs.");
addQ("static-voltage-regulators", "What kind of control and sensing is used in Krykard static voltage regulators?", "Krykard static voltage regulators use 20 kHz high-speed digital controllers with True RMS sensing, ensuring accurate voltage regulation under distorted waveforms.");
addQ("static-voltage-regulators", "What maintenance is required for Krykard static voltage regulators?", "Krykard static voltage regulators don't require routine maintenance due to the absence of mechanical components.");
addQ("static-voltage-regulators", "What is the expected service life of Krykard static voltage regulators?", "With proper design and operating conditions, Krykard static voltage regulators provide long, reliable service life in industrial applications of 15 - 20 Years.");
addQ("static-voltage-regulators", "Are Krykard static voltage regulators suitable for clean-room or noise-sensitive environments?", "Yes. Krykard static voltage regulators operate silently and are well suited for clean-room applications such as hospitals, research laboratories and noise-sensitive environments.");
addQ("static-voltage-regulators", "IGBT-Based Krykard Static Voltage Stabilizer – Uses & Applications", "Key Applications: Industrial (CNC machines, Robotics & automation lines, Injection moulding machines, PLC / SCADA systems), Medical (MRI, CT Scan, X-ray machines, Diagnostic equipment), Commercial & IT (Data centres, Semiconductor manufacturing, R&D laboratories), Infrastructure & Utilities.");
addQ("static-voltage-regulators", "Are Krykard static voltage regulators BIS compliant?", "There is no specific BIS/IS Standard currently published exclusively for static voltage regulators. Krykard will comply with them as and when they are published. Krykard static voltage regulators are compliant as per IS 9815.");
addQ("static-voltage-regulators", "Are Krykard static voltage regulators CE compliant?", "Yes. Krykard static voltage regulators are CE compliant, meeting applicable European safety and EMC directives.");
addQ("static-voltage-regulators", "Is Krykard an ISO certified manufacturer of static voltage regulators?", "Yes. Krykard operates under an ISO 9001:2015 certified Quality Management System. Our factory is also ISO 14001:2015 and ISO 45001:2018 compliant.");
addQ("static-voltage-regulators", "Do Krykard static voltage regulators meet EMC and electrical safety standards?", "Yes. Krykard static voltage regulators are designed to meet applicable EMC, insulation, earthing, and electrical safety norms for industrial equipment.");
addQ("static-voltage-regulators", "Can Krykard provide test reports and compliance documentation?", "Yes. Krykard can provide routine test reports, compliance declarations, and supporting documentation for projects, exports, and tenders.");

// 2. Servo Stabilisers
addQ("servo-stabilisers", "What is a Servo Controlled Voltage Stabiliser?", "Servo Controlled Voltage Stabiliser is an industrial grade voltage regulation system designed to provide precise, stable voltage for sensitive and heavy-duty capital equipment, even under wide voltage fluctuations from the utility supply.");
addQ("servo-stabilisers", "How does servo voltage stabiliser work?", "Servo Stabilisers continuously monitor the output voltage using True RMS sensing. Any deviation is corrected by a precision servo motor that adjusts the variable transformer winding to maintain a constant voltage output.");
addQ("servo-stabilisers", "Why choose Krykard servo stabilisers over conventional stabilisers?", "Krykard servo stabilisers are engineered with efficient transformers using high purity Copper & Aluminium windings, industrial servo motors, robust control electronics, and comprehensive protection systems. Krykard offers ±1% voltage regulation, making them ideal for CNC machines, VFD-driven equipment, medical systems, IT infrastructure and automation panels. Conventional stabilisers offer only ±10% regulation.");
addQ("servo-stabilisers", "What input voltage ranges are available in Krykard servo stabilisers?", "Krykard servo stabilisers are available with wide input ranges such as ±12%, ±17%, ±22% of 230V (1 phase models) or 400V (3 phase models). Other custom ranges are also provided depending on application requirements.");
addQ("servo-stabilisers", "Why is True RMS sensing important in servo stabilisers?", "True RMS sensing ensures accurate voltage measurement under distorted waveforms, protecting modern electronic equipment from improper voltage correction.");
addQ("servo-stabilisers", "Are Krykard servo stabilisers suitable for CNC machines and VFD loads?", "Yes. Krykard stabilisers use True RMS voltage sensing with high sampling rates, ensuring accurate voltage control and regulation even with distorted waveforms from CNC machines, VFDs, and SMPS-based loads.");
addQ("servo-stabilisers", "Do Krykard servo stabilisers generate harmonics?", "No. Krykard servo stabilisers are electro-mechanical systems and therefore maintain a sinusoidal output voltage that is a replica of the Input waveform, without introducing any switching harmonics.");
addQ("servo-stabilisers", "What is the efficiency of Krykard servo controlled voltage stabilisers?", "Krykard servo stabilisers typically achieve 97–99% efficiency, depending on the kVA rating, ensuring minimal losses and reduced operating costs.");
addQ("servo-stabilisers", "Can Krykard servo stabilisers handle motor starting and inrush currents?", "Yes. Krykard stabilisers are designed to handle high inrush currents associated with motors, compressors, transformers, and heavy industrial machinery.");
addQ("servo-stabilisers", "Are Krykard servo stabilisers available in three-phase unbalanced versions?", "Yes. Krykard manufactures three-phase unbalanced servo stabilisers that independently regulate each phase for maximum protection.");
addQ("servo-stabilisers", "Can KRYKARD servo stabilisers be used for residential applications?", "Yes. KRYKARD Servo Stabilizers can be used for residential applications. They provide stable voltage output to protect home appliances, smooth servo motor correction, low noise operation, and high efficiency.");
addQ("servo-stabilisers", "Can Krykard servo stabilisers operate with DG sets?", "Yes. Krykard servo stabilisers are fully compatible with diesel generator (DG) power and help stabilise voltage during sudden load variations.");
addQ("servo-stabilisers", "What protection features are provided in Krykard servo stabilisers?", "Standard protections include: Over-voltage and under-voltage cut-off, Overload and short-circuit protection, Single-phasing and phase-sequence protection (3-phase). Optional features include High E-N Voltage cut-off, Input High Voltage cut-off, High/Low Frequency cut-off, and Over temperature cut-off.");
addQ("servo-stabilisers", "What are the site requirements for installing a servo stabiliser?", "Installation requires adequate ventilation, proper earthing, sufficient clearance for maintenance, and a dust-free environment for optimal performance. For dusty environments, Krykard makes custom built Air cooled and Oil cooled units.");
addQ("servo-stabilisers", "Can KRYKARD servo stabilisers be installed outdoors?", "Yes, Krykard makes custom built Air cooled and Oil cooled units with higher IP class of enclosures suitable for outdoor use (IP 54 / IP 55).");
addQ("servo-stabilisers", "What maintenance is required for Krykard servo stabilisers?", "Routine maintenance involves periodic inspection of carbon brushes, cleaning of transformer windings, and checking servo motor operation, usually at least once in six months.");
addQ("servo-stabilisers", "What is the expected service life of Krykard servo stabilisers?", "With proper installation and periodic preventive maintenance, Krykard servo stabilisers typically offer 15–20 years of reliable industrial service.");
addQ("servo-stabilisers", "What industries commonly use Krykard servo stabilisers?", "Krykard servo stabilisers are widely used in CNC machining, textiles, printing, packaging, medical equipment, data centres, retail stores and industrial automation.");
addQ("servo-stabilisers", "Why Buy KRYKARD Servo Stabilizers?", "40+ Years of Expertise – Decades of engineering excellence. 5+ Lakh Installations – Widely used across industries. Proven Design – Time-tested technology. Reliable Performance – Consistent voltage regulation and protection. 110+ Service Centres – Strong nationwide support.");
addQ("servo-stabilisers", "Are Krykard servo stabilisers tested as per BIS standards?", "Krykard servo stabilisers are designed and manufactured in compliance with relevant Indian Standards (IS 9815:1994) and BIS requirements. Samples have been type tested at CPRI Bangalore.");
addQ("servo-stabilisers", "Are Krykard servo stabilisers CE compliant?", "Yes. Krykard servo stabilisers are CE compliant, meeting applicable European directives related to safety, electromagnetic compatibility (EMC), and low-voltage operation.");
addQ("servo-stabilisers", "Is Krykard an ISO certified manufacturer?", "Yes. Krykard operates under an ISO 9001:2015 certified Quality Management System. Our factory is also ISO 14001:2015 and ISO 45001:2018 compliant.");
addQ("servo-stabilisers", "Do Krykard stabilisers comply with electrical safety and EMC norms?", "Yes. Krykard stabilisers are designed to comply with applicable electrical safety, insulation, earthing, and EMC requirements for industrial installations.");
addQ("servo-stabilisers", "Can Krykard provide test certificates and compliance documents?", "Yes. Krykard can provide routine test reports, type test references, compliance declarations, and quality documents as required for projects and tenders.");
addQ("servo-stabilisers", "How do I choose the right capacity (KVA) for my equipment?", "Sum up the total load, convert kW to KVA using KVA = kW / Power Factor (usually 0.8). Choose a stabilizer with at least 10–20% higher capacity than your total load. Reach out to our team for assistance.");
addQ("servo-stabilisers", "Single-phase or Three-phase Stabilizer?", "Single-phase: For home appliances, small labs, or office equipment (230V). Three-phase: For industrial machinery, large HVAC systems, or medical equipment (400V).");
addQ("servo-stabilisers", "How do I determine the Input voltage Range?", "For LT Consumers: 230V / 415V supply, recommended 1-phase 170-270V or 3-phase 310-480V. For HT Consumers: 3-phase 3.3kV or above, recommended 1-phase 190-250V or 3-phase 360-480V.");

// 3. Isolation Transformers
addQ("isolation-transformers", "What is an Isolation Transformer?", "Isolation Transformer electrically isolates the primary and secondary circuits to improve safety, noise immunity, and power quality for industrial machines and data-centre loads.");
addQ("isolation-transformers", "Why are isolation transformers used in industrial and data-center applications?", "They help reduce common-mode noise, improve equipment protection, enhance safety against earth faults, and provide a clean voltage reference for sensitive equipment. In addition, isolation transformers are also used to step up or step down voltages.");
addQ("isolation-transformers", "What types of isolation transformers does Krykard manufacture?", "Krykard manufactures Standard Isolation Transformers, Ultra Isolation Transformers, and K-Rated Isolation Transformers (only 3 phase) in both single-phase and three-phase configurations.");
addQ("isolation-transformers", "Does Krykard specialize in three-phase isolation transformers?", "Yes. Krykard has extensive experience in three-phase isolation transformers for CNC/VMC machines, automation systems, UPS installations, and data centres.");
addQ("isolation-transformers", "Does Krykard make transformers for only Step-up / Step-down voltage applications?", "Yes, in cases where primary - secondary isolation is not a mandatory requirement, Krykard offers Step-up / Step-down auto-transformers that are compact in size and more economical.");
addQ("isolation-transformers", "How to Choose Between an Isolation Transformer and an Auto-transformer?", "Isolation transformer: Use when galvanic separation is needed (e.g., medical environments, data centres). Auto-transformer: Use for simple voltage adaptation where galvanic isolation is not required.");
addQ("isolation-transformers", "Is copper a better winding material than aluminum in a transformer?", "No. Krykard manufactures both Aluminium and Copper wound transformers using a resistance-matched design approach. Electrical and thermal performance remain comparable, and the choice is left to the consultant or buyer.");
addQ("isolation-transformers", "What is an Ultra Isolation Transformer?", "An Ultra Isolation Transformer is designed with enhanced insulation systems, electrostatic shielding, and increased creepage and clearance distances to achieve superior noise attenuation and safety.");
addQ("isolation-transformers", "Where are Ultra Isolation Transformers typically used?", "They are commonly used for: Precision CNC & VMC machines, Medical and laboratory equipment, Sensitive automation and control systems, High electrical noise environments.");
addQ("isolation-transformers", "What is a K-Rated Isolation Transformer?", "A K-Rated Isolation Transformer is designed to safely handle harmonic currents generated by nonlinear loads such as UPS systems, VFDs, IT equipment, and data-centre loads.");
addQ("isolation-transformers", "What are the common K rating available in Krykard isolation transformers?", "Krykard offers K-4, K-9, K-13, and higher K-rated transformers, depending on harmonic levels and application requirements.");
addQ("isolation-transformers", "What core and insulation materials are used in Krykard isolation transformers?", "Krykard uses high-grade CRNGO steel cores for standard isolation transformers and CRGO / silicon steel cores for K rated transformers, electrolytic copper or aluminium conductors, and Class-H insulation systems.");
addQ("isolation-transformers", "Do Krykard isolation transformers help reduce electrical noise?", "Yes. Krykard isolation transformers significantly reduce common-mode noise and transients by providing electrostatic shielding.");
addQ("isolation-transformers", "Is dedicated earthing required on the secondary side of a Krykard Isolation Transformer?", "Yes. For industrial machines and data-centre applications, Krykard strongly recommends providing a dedicated earth reference on the secondary side for proper noise reduction and safety.");
addQ("isolation-transformers", "Can Krykard isolation transformers be customized?", "Yes. Krykard offers customisation for: Voltage ratios, kVA ratings, Al or Cu windings, Shielding level, Enclosure IP rating, Cooling method.");
addQ("isolation-transformers", "Are Krykard isolation transformers suitable for CNC and VMC machines?", "Yes. Krykard isolation transformers are widely used with CNC, VMC, laser cutting, and industrial automation machines.");
addQ("isolation-transformers", "What cooling methods are available?", "Krykard isolation transformers are available as: Natural air-cooled (AN), Forced air-cooled (AF), Natural oil-cooled (ONAN).");
addQ("isolation-transformers", "What protection and monitoring features are provided?", "Depending on application, Krykard transformers can be supplied with: Input & Output Breakers, Soft Starters, Thermal sensors & Over-temperature alarms, Multifunction meters with or without communication port.");
addQ("isolation-transformers", "Are Krykard isolation transformers BIS compliant?", "Krykard isolation transformers are designed and manufactured in compliance with relevant Indian Standards (IS 2026 Part 11) and BIS requirements.");
addQ("isolation-transformers", "Are Krykard isolation transformers CE compliant?", "Yes. Krykard isolation transformers are CE compliant, meeting applicable European safety and EMC directives.");
addQ("isolation-transformers", "Is Krykard an ISO certified transformer manufacturer?", "Yes. Krykard operates under an ISO 9001:2015 certified Quality Management System. Our factory is also ISO 14001:2015 and ISO 45001:2018 compliant.");
addQ("isolation-transformers", "Can Krykard provide test certificates and compliance documentation?", "Yes. Krykard provides routine test certificates, compliance declarations, and supporting documentation for industrial and data-centre projects.");
addQ("isolation-transformers", "What is the average lifespan of an KRYKARD isolation transformer?", "KRYKARD isolation transformers are designed for an operational life of at least 15 to 20 years under normal conditions. The quality of materials and strict quality controls ensure long-term reliability.");
addQ("isolation-transformers", "Why do KRYKARD isolation transformers use windings with Class H Insulation?", "Class H insulation is rated for 180°C continuous operation and provides better long-term durability. It reduces the risk of insulation breakdown, increases transformer lifespan, and is ideal for 24x7 industrial applications and data centers.");

// 4. ALENSOFT EnMS
addQ("alensoft-enms", "What is ALENSOFT EMS (ERMS)?", "ALENSOFT Energy & Resource Management System (ERMS) is a comprehensive, AI-ready digital platform for real-time monitoring, historical analysis, and optimization of energy and utilities across industrial facilities. It consolidates data from multiple meters and utilities onto a single, intuitive web-based portal.");
addQ("alensoft-enms", "What utilities can ALENSOFT EMS monitor?", "ALENSOFT EMS supports WAGES utilities: Electricity, Water, Compressed Air, Gas, Steam, Fuels. All utilities are monitored using a common architecture, dashboards, and reporting framework.");
addQ("alensoft-enms", "How is energy and utility data collected in ALENSOFT EMS?", "Energy and utility data is collected from digital meters and field devices installed across the shopfloor. These meters communicate with SMART Gateways, which act as intelligent data loggers and Modbus master collectors, aggregating data before securely transmitting it to the ALENSOFT server.");
addQ("alensoft-enms", "What is a SMART Gateway and why is it important?", "A SMART Gateway is an intelligent edge device that connects Modbus RTU and/or Modbus TCP/IP devices natively, polls data from meters at configurable intervals, performs on-board data logging, and automatically syncs data with the server. SMART Gateways ensure 100% data availability, even during LAN or network interruptions.");
addQ("alensoft-enms", "Can non-Modbus meters be integrated into ALENSOFT EMS?", "Yes. Any meter or device with a digital communication output can be integrated directly if it supports Modbus or via protocol converters if it uses a non-Modbus protocol. This ensures flexibility in integrating both existing and new field devices.");
addQ("alensoft-enms", "Is ALENSOFT EMS available as On-Premise or Cloud?", "Yes. ALENSOFT EMS supports both deployment models: On-Premise (installed on a customer-owned server, license-based) and Cloud (SaaS) (Hosted and managed centrally, subscription-based).");
addQ("alensoft-enms", "How does ALENSOFT EMS ensure no data loss?", "ALENSOFT ensures data reliability through: On-board data logging in SMART Gateways, Auto-sync of logged data to the server, Robust LAN / cloud communication mechanisms. This architecture ensures no missing or corrupted data at the hardware level.");
addQ("alensoft-enms", "What kind of data can users monitor in real time?", "Users can monitor: All basic electrical parameters (Voltage, current, power, power factor), Energy consumption and demand, Harmonics and power quality indicators, Alarms and alerts, Equipment and feeder-level parameters. All data is available via real-time dashboards, trends, grids, and cards.");
addQ("alensoft-enms", "Does ALENSOFT EMS support historical data analysis?", "Yes. ALENSOFT EMS provides extensive historical analysis including: Minute, hourly, daily, monthly, and yearly trends, Consumption analysis and comparisons, Peak demand and TOD analysis, Energy flow and resource flow visualization.");
addQ("alensoft-enms", "What dashboards are available in ALENSOFT EMS?", "ALENSOFT EMS includes: Real-time monitoring dashboards, Historical analytics dashboards, Self-service BI dashboards, Power flow and Sankey-style visualizations, Multi-location bird's-eye views. Dashboards are fully configurable and role-based.");
addQ("alensoft-enms", "What reports does ALENSOFT EMS provide?", "ALENSOFT EMS offers: Daily, weekly, and monthly reports, e-Log Books, Consumption and group consumption reports, Peak demand and TOD reports, Power interruption and network health reports. All reports are exportable to Excel/PDF and schedulable.");
addQ("alensoft-enms", "Can ALENSOFT EMS help identify energy losses?", "Yes. ALENSOFT EMS supports energy accounting from incomers to feeders and load points, enabling: Identification of technical and operational losses, Comparison of source vs consumption, Detection of abnormal energy behavior.");
addQ("alensoft-enms", "How does alarm and alert management work in ALENSOFT EMS?", "ALENSOFT EMS provides: Threshold-based alarms, Severity categorization, Acknowledgement workflows, Alarm history and analytics, Email / messaging notifications via e-mail and WhatsApp (optional).");
addQ("alensoft-enms", "Is ALENSOFT EMS scalable for large installations?", "Yes. ALENSOFT EMS is designed to scale: From a few meters to thousands of devices, Across multiple plants and locations, With distributed SMART Gateways and centralized analytics. Scalability is built into both hardware and software layers.");
addQ("alensoft-enms", "How secure is ALENSOFT EMS?", "ALENSOFT EMS includes: Secure LAN / HTTPS communication, Role-based user access, Controlled server ports and APIs, On-premise data ownership (if required). Security and data integrity are core design principles.");
addQ("alensoft-enms", "Can ALENSOFT EMS integrate with other enterprise systems?", "Yes. ALENSOFT EMS can integrate with: SCADA / PLC / BMS systems, SAP, ERP and MIS platforms, ESG, sustainability, and AI modules. Integration is enabled through standard APIs and industrial protocols.");
addQ("alensoft-enms", "Does ALENSOFT EMS support ISO 50001 and audits?", "Yes. ALENSOFT EMS is designed to support: ISO 50001 energy management requirements, Audit-ready data and reports, Baseline tracking and performance analysis. This significantly reduces audit preparation effort.");
addQ("alensoft-enms", "Is ALENSOFT EMS future-ready for AI and advanced analytics?", "Yes. ALENSOFT EMS is built as a future-ready digital foundation, supporting: Dr. ALEN, an AI enabled chatbot that supports voice and text input, AI-driven insights and recommendations, Predictive analytics, Daily dashboards and decision support, Advanced equipment optimization modules.");

// 5. UPS Systems
addQ("ups", "Why is online double conversion mandatory for critical loads?", "Utility power in industrial and IT environments is affected by motor starting, switching transients, harmonics, voltage dips, and frequency variations. Online double-conversion ensures the load is continuously supplied by the inverter, independent of input conditions, preventing PLC resets, server crashes, and process interruptions during voltage sags, surges, and grid instability.");
addQ("ups", "Why is galvanic isolation required in industrial UPS systems?", "Industrial sites typically have multiple earthing points, long cable runs, and high common-mode noise levels. Without electrical isolation, faults or noise on the input side can directly transfer to the load, increasing the risk of equipment damage. Galvanic isolation breaks the electrical path between input and output, improving safety and reliability.");
addQ("ups", "Why are high input power factor and low THDi important at system level?", "Non-linear loads draw distorted current, causing overheating of transformers, cables, and generators. A UPS with high PF and low THDi makes the UPS behave like a near-linear load, enabling smaller generators, reducing losses, and ensuring stable generator operation.");
addQ("ups", "Why must a UPS support unbalanced and mixed loads?", "In real installations, loads are rarely evenly distributed across phases due to single-phase IT loads, lighting, and auxiliary equipment. UPS systems designed only for balanced conditions may overheat or trip. Support for unbalanced loads ensures stable voltage on all phases and reliable operation.");
addQ("ups", "Why is output voltage regulation critical?", "Electronic equipment is designed to operate within narrow voltage limits. Repeated exposure to voltage deviation accelerates component aging and causes intermittent failures. Tight output voltage regulation improves long-term reliability of servers, VFDs, instrumentation, and control systems.");
addQ("ups", "Why is pure sinusoidal output essential?", "Distorted waveforms increase RMS current and cause excess heating in connected equipment. Non-sinusoidal output reduces efficiency and stresses transformers, motors, and SMPS power supplies. A clean sinewave ensures compatibility with all load types and prevents overheating and premature failures.");
addQ("ups", "Why is high overload capability engineered into the UPS?", "Loads such as motors and SMPS draw high inrush current during startup or recovery. UPS systems with limited overload capacity may transfer to bypass or shut down unnecessarily. High overload capability allows smooth load startup and maintains power continuity during transient conditions.");
addQ("ups", "Why must efficiency be balanced with thermal design?", "Power electronics failures are often caused by thermal stress rather than electrical overload. High efficiency alone is insufficient without proper heat dissipation and thermal control. Balanced thermal design extends component life and reduces unplanned shutdowns, especially in high-temperature environments.");
addQ("ups", "Why is intelligent battery management essential?", "Batteries degrade silently and often fail without warning. Uncontrolled charging and temperature variation significantly shorten battery life. Intelligent battery management ensures predictable backup time and reliable operation during actual power outages.");
addQ("ups", "Why is flexible battery configuration required?", "Different applications require different backup durations—from short ride-through to long process continuity. Fixed battery configurations force oversizing or limit system usability. Flexible configurations optimize cost, footprint, and backup time without redesigning the UPS.");
addQ("ups", "Why is parallel redundancy designed at the architecture level?", "In critical applications, downtime during maintenance or failure is unacceptable. Single UPS systems represent a single point of failure. Parallel redundancy ensures continuous power availability even during maintenance or module failure.");
addQ("ups", "Why are multiple communication interfaces necessary?", "Modern facilities rely on centralized monitoring and predictive maintenance. UPS systems without communication capability delay fault detection and corrective action. Integration with BMS, SCADA, and monitoring platforms enables proactive maintenance and faster response.");
addQ("ups", "Why must a UPS tolerate harsh environmental conditions?", "Industrial environments experience high temperature, dust, humidity, and altitude variations. Environmental stress directly affects insulation life and semiconductor performance. Industrial-grade design ensures consistent performance outside controlled data-center conditions.");
addQ("ups", "Why are MTBF and serviceability key design priorities?", "UPS failure impacts operations, safety, and revenue. Slow diagnosis and repair extend downtime. High MTBF and service-friendly design reduce recovery time and lifecycle cost.");
addQ("ups", "Why is UPS design application-driven rather than feature-driven?", "UPS systems are often selected based on specifications rather than real operating conditions. Features without application relevance do not improve reliability. Application-driven design ensures predictable performance under real-world electrical and environmental conditions.");

// 6. Power Quality Analyzers
addQ("power-quality-analyzers", "What range of PQ analyzers are available with KRYKARD?", "KRYKARD offers a wide range of power quality analyzers including 3‑phase 3‑channel analyzers and 4‑channel (4U/4I) power analyzers suitable for power and energy audits. The current portable range includes models such as ALM 20, ALM 31, ALM 33, ALM 36 and CA 8345.");
addQ("power-quality-analyzers", "Do KRYKARD PQ analyzers comply with IEC 61000‑4‑30?", "Yes, KRYKARD PQ analyzers such as ALM 31, ALM 33 and ALM 36 comply with IEC 61000‑4‑30 measurement standards (Class B) for power quality measurements. The CA 8345 model is a Class A power quality analyzer designed to meet IEC 61000‑4‑30 Class A Edition 3 requirements.");
addQ("power-quality-analyzers", "Does KRYKARD have an IEC 61000‑4‑30 Class A Ed‑3 certified product?", "Yes, the CA 8345 model is a Class A Edition 3 compliant power quality analyzer, suitable for high‑end power quality investigations and compliance reporting.");
addQ("power-quality-analyzers", "What is the battery backup time and memory capacity of PQ analyzers?", "Portable PQ analyzers such as the ALM‑31 family typically offer long battery backup suitable for a full working day (up to around 10–13 hours depending on model and usage). Models like ALM 20/31/36 provide internal memory for extended logging, while the CA 8345 offers high‑capacity internal memory (up to tens of gigabytes) for long‑term Class A recording.");
addQ("power-quality-analyzers", "Does KRYKARD supply PQ reporting software along with PQ analyzers?", "Yes, all KRYKARD PQ analyzers are supplied with DataView software (and related PQ software tools) for easy configuration, data download and report generation. The software enables one‑click export to Excel, automated EN 50160 / IEC‑based analysis and generation of professional PQ and energy audit reports.");

// 7. Multifunction & Power Quality Meters
addQ("multifunction-power-quality-meters", "Does KRYKARD have multifunction power meters?", "Yes, KRYKARD offers a wide range of multifunction power and energy meters, including panel load managers, harmonic meters, demand controllers, prepaid meters and DIN-rail meters for LV and MV panels.");
addQ("multifunction-power-quality-meters", "What is the accuracy level of multifunction power meters?", "KRYKARD multifunction and energy meters are available in Class 1, Class 0.5S and Class 0.2S accuracy classes, suitable for both monitoring and high-accuracy energy management applications.");
addQ("multifunction-power-quality-meters", "What application categories do KRYKARD multifunction meters serve?", "KRYKARD meters cover multiple application categories, including: Energy meters for feeder, panel and utility monitoring, Demand controllers for load management and demand control, Harmonic meters and power quality meters for harmonics and PQ monitoring, Prepaid energy meters for tenant and sub-metering applications, DIN-rail energy meters for compact distribution boards and OEM panels, and IoT-enabled energy meters and panel load managers for cloud-based monitoring and analytics.");
addQ("multifunction-power-quality-meters", "Does KRYKARD have power quality monitoring meters?", "Yes, KRYKARD offers power quality monitoring meters and Class A compliant PQ monitors that capture events such as sags, swells, transients and rapid voltage changes. These meters are designed for continuous PQ monitoring in critical facilities like data centers, process plants and commercial buildings.");
addQ("multifunction-power-quality-meters", "Does KRYKARD have gateway and IoT solution-based meters?", "Yes, KRYKARD offers IoT gateways with 4G and Ethernet connectivity, supporting protocols such as MQTT and Modbus for integration with cloud platforms and SCADA. These gateways work with KRYKARD meters to provide centralized, web-based energy and power quality dashboards with built-in data logging.");

// 8. Thermal Imaging & Cameras
addQ("thermal-imaging-cameras", "Does KRYKARD have economical thermal imager models for daily use?", "Yes, KRYKARD offers economical thermal imaging solutions including Android plug-in, wireless and compact handheld thermal imagers for day-to-day electrical and maintenance inspections.");
addQ("thermal-imaging-cameras", "Does KRYKARD have pocket-size thermal cameras?", "Yes, KRYKARD has a range of pocket-size thermal imagers with advanced specifications, suitable for service engineers and facility maintenance teams.");
addQ("thermal-imaging-cameras", "Does KRYKARD have autofocus, GPS-based cameras?", "Yes, KRYKARD offers thermal camera series such as the TC4xxx range with features like autofocus and integrated GPS for geo-tagged thermography reports.");
addQ("thermal-imaging-cameras", "Does KRYKARD have camcorder models?", "Yes, KRYKARD has a wide range of thermal camcorder-style cameras, such as the TC7xxx series, designed for advanced thermography and detailed reporting.");

// 9. Installation & Safety Testers
addQ("installation-safety-testers", "Does KRYKARD have insulation testers, earth testers and multifunction installation testers?", "Yes, KRYKARD offers a wide range of insulation testers from 1 kV up to 15 kV for electrical maintenance and high-voltage equipment testing. KRYKARD provides 2-pole, 3-pole and 4-pole earth resistivity testers, clamp-on earth/earth-loop testers with memory, Bluetooth and reporting software for modern installation testing. There is also a comprehensive range of multifunction installation testers for testing continuity, insulation, loop impedance, RCDs and overall installation safety in accordance with international standards.");
